Adjust Systems to use `TensorTable` and schema shapes
NVIDIA-Merlin/systems pull request #293
Opened 2023-03-07 21:13 UTC by karlhigley

2023-03-07 21:15 UTC, karlhigley commented on merlin/systems/dag/ops/session_filter.py
> +        filtered_results = candidate_ids.values[~np.isin(candidate_ids.values, filter_ids.values)]
This is a workaround since `TensorColumn` doesn't support indexing with a boolean array yet

2023-03-07 21:24 UTC, jperez999 requested changes

2023-03-07 21:24 UTC, jperez999 commented on merlin/systems/dag/ops/pytorch.py
> +            transformable = tensor_table_from_df(transformable)
I think we can just use the class here, TensorTable.from_df(transformable)

2023-03-07 21:24 UTC, jperez999 commented on merlin/systems/dag/ops/pytorch.py
> +            output = df_from_tensor_table(output)
here we should use output.to_df()

2023-03-07 21:24 UTC, jperez999 commented on merlin/systems/dag/ops/workflow.py
> +            transformable = df_from_tensor_table(transformable)
TensorTable.from_df(transformable)

2023-03-07 21:24 UTC, jperez999 commented on merlin/systems/dag/ops/workflow.py
> +            output = tensor_table_from_df(output)
TensorTable.from_df(output)

2023-03-07 21:24 UTC, jperez999 commented on tests/unit/systems/dag/runtimes/local/ops/fil/test_sklearn.py
> +    dict_array = tensor_table_from_df(request_df)
TensorTable.from_df(request_df)

2023-03-07 21:24 UTC, jperez999 commented on tests/unit/systems/dag/runtimes/local/ops/fil/test_sklearn.py
> +    dict_array = tensor_table_from_df(request_df)
TensorTable.from_df(request_df)

2023-03-07 21:24 UTC, jperez999 commented on tests/unit/systems/dag/runtimes/local/ops/fil/test_xgboost.py
> +    dict_array = tensor_table_from_df(request_df)
TensorTable.from_df(request_df)

2023-03-07 21:24 UTC, jperez999 commented on tests/unit/systems/dag/runtimes/local/ops/fil/test_xgboost.py
> +    dict_array = tensor_table_from_df(request_df)
TensorTable.from_df(request_df)

2023-03-07 21:24 UTC, jperez999 commented on tests/unit/systems/ops/faiss/test_executor.py
> +    # assert isinstance(response, TensorTable)
delete this comment

2023-03-17 14:18 UTC, oliverholworthy approved these changes

2023-03-17 15:14 UTC, merged